import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import AuthProvider from "./components/AuthProvider";
import KeepAlive from "./components/keep-alive";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Explore With Locals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {/* <DebugAuth /> */}
          <Header />
          <KeepAlive />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
